### ISSUE TITLE
Shall we ship this thing?

### ISSUE THREAD

**Issue by martinthomson** [martinthomson/http-replay#12]
Let's all give this a read over and see if it remains sane, but I think we're good enough for a -00.  Agree?

**Comment by mnot** [comment]
Just did a PR that makes me happy, please have a look.

> An intermediary MUST NOT use early data when forwarding a request unless early data was used on a previous hop. 

Is this requirement really necessary now?

**Comment by wtarreau** [comment]
I think it can be relaxed this way : ... MUST NOT use ... unless early data was used on a previous hop or the intermediary is capable of retrying the request when facing a 4NN (Too Early) status code. That gives it the same freedom as any client and will suit CDN use cases I think.

**Comment by martinthomson** [comment]
I think that the requirement is always valid.  It takes the choice about replay-safety away from the clients of the intermediary.  I might be convinced to relax this to a "MUST NOT ... unless the intermediary knows that replaying this particular request is safe to retry" on the basis that the intermediary might have out-of-band information from the origin server about the request/resource.

**Comment by wtarreau** [comment]
Well, the intermediary here is in the same position as the client : it doesn't know, tries its chance and relies on 4NN if the server wasn't willing to accept the risk. By definition it's the server which judges whether it's retriable or not since 4NN indicates it was not processed, hence safe to retry.

**Comment by mnot** [comment]
Suggest:

> An intermediary MUST NOT use early data when forwarding a request unless early data was used on a previous hop, or it knows that the server will generate 4NN (Too Early) appropriately (typically, using out-of-band configuration).

**Comment by martinthomson** [comment]
The contract that I think we're aiming for is that both client and server agree to the risk that the request is replayed.  I don't think that the intermediary should be making that decision for the client.  Note that even if the server correctly generates 4NN, there is a risk of replay, even just by retrying after 4NN.

**Comment by mnot** [comment]
Hmm. I like the symmetry of the client/server buy-in thing, just not sure it's necessary.

**Comment by mnot** [comment]
Specifically, if a CDN has an agreement with their client that they'll use early data for forwarded requests, they're not going to care what the spec says.

**Comment by martinthomson** [comment]
I think that it might be sufficient to have out-of-band configuration for replay safety, but not for support of 4NN.

**Comment by martinthomson** [comment]
How about: 

> An intermediary MUST NOT use early data when forwarding a request unless early data was used on a previous hop, or it knows that the request can be retried safely without consequences (typically, using out-of-band configuration).

**Comment by wtarreau** [comment]
A few other points (let me know if it's better not to use this issue for discussion) : 
- "Clients MUST NOT use early data in requests when a proxy is configured." => after giving it some thoughts, that's perfectly fine with the CONNECT method (only way for now to transport TLS). We wrote this initially when we wanted to send the Early-Data header field from the client, so this doesn't seem necessary anymore ;

- "Early-Data header field is added/included to any request that is received in early data" => "that is conveyed in early data" (it can have been on the other side of the gateway, same term used later)

- We should remove all references to value 0 for Early-Data since the simple presence of the header field indicates early data was used at least once. I've already found another header field for which only value "1" is permitted, so this would not be something new ;

- may we recommend that the 4NN Too early payload will not be displayed and should remain as small as possible to speed up a retry ?

**Comment by mnot** [comment]
@martinthomson that's what I was just typing...

**Comment by wtarreau** [comment]
sorry but presence of the Early-Data header field mandates support for 4NN by someone along the chain. However I totally agree with one point mentionned in the draft already which is that a request received as early data must not be replayed by an intermediary (since it's probably not safe already).

**Comment by martinthomson** [comment]
OK, we have that solved, it's narrower, but better for it.

I don't remember adding the proxy suggestion, I think we can remove it.

I can make a PR for the text suggestion.  Do we want to remove "0" entirely?  It seems like it might be OK.

I think that the payload suggestion is obvious enough, but we can note that this will likely never be rendered.

**Comment by mnot** [comment]
* proxy -- I think I agree. 

* conveyed -- that has a very different meaning; it implies that UAs must sent ED

* 0 -- I think I agree.

* display -- hmm. We generally avoid talking about that sort of thing around here...

**Comment by martinthomson** [comment]
Re conveyed, the "received" thing was intentional, I think that I'd prefer to keep it.

I'll do a PR for all except the "display" thing.

**Comment by wtarreau** [comment]
@mnot regarding "conveyed", I wanted to make it clearer that the presence of the field indicates that this request's safety was not guaranteed along the whole chain, regardless of the fact that the one observing this field didn't receive it as early data.

OK for "display" that's not the appropriate term, Martin uses "rendered" which is more appropriate. Sending a small PR for two minor things now.

**Comment by martinthomson** [comment]
I've merged the PR, which leaves the "displayed" thing.  Given that it's only advice, I think that we can leave it out for now, preferring a shorter, succinct document when there is doubt.

**Comment by mnot** [comment]
🚢  it 🚢  it 🚢  it

**Comment by martinthomson** [comment]
@wtarreau ?

**Comment by wtarreau** [comment]
Still reading. Sorry if I'm slower

**Comment by wtarreau** [comment]
Still having a wording issue here : " server can trigger a retry without the use of early data by responding with the 4NN" (probably because i'm not native english speaker). I'd like "s/the use of/processing/" to clarify it.

**Comment by wtarreau** [comment]
"max_early_data_size field" => field of what ? Isn't is a TLS setting or something related to the TLS API maybe ? At least it's not a header field.

**Comment by wtarreau** [comment]
Otherwise looks perfect to me :-)

**Comment by martinthomson** [comment]
> Still having a wording issue here : " server can trigger a retry without the use of early data by responding with the 4NN" (probably because i'm not native english speaker). I'd like "s/the use of/processing/" to clarify it.

How about:

> The server can cause a client to retry a request and not use early data by ....

max_early_data_size field of the early_data TLS extension.  I'll fix that directly.

**Comment by wtarreau** [comment]
OK for both, thanks!

**Comment by martinthomson** [comment]
Ships ahoy!

**Comment by wtarreau** [comment]
Thanks both for this great and efficient work session ;-)

**Comment by mnot** [comment]
🎉
